### ISSUE TITLE
Laravel 8 support?

### ISSUE THREAD

**Issue by MACscr** [ptejada/laravel-mailgun-options#2]
Would really like to have laravel 8 support. This also works with the api method of submission and doesnt require smtp, correct?

**Comment by ptejada** [comment]
@MACscr 
If I recall correctly the Laravel mailgun integration exclusively uses their API. Is very likely that this package works with Laravel 8. I personally have not tested it but it should be easy to add to the test suite.

**Comment by MACscr** [comment]
Yep, I got it to work when I just manually installed the trait versus using the package. Thanks!

- Mark
